{
  try {
    reportError.report(e);
  }
 catch (  Exception ex) {
    LOG.error("Error while reporting error to cluster, proceeding with shutdown",ex);
  }
  if (Utils.exceptionCauseIsInstanceOf(InterruptedException.class,e) || Utils.exceptionCauseIsInstanceOf(java.io.InterruptedIOException.class,e)) {
    LOG.info("Got interrupted exception shutting thread down...");
    suicideFn.run();
  }
}
